# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/wifipmod_PmodWIFI_0_0.xci
# IP: The module: 'wifipmod_PmodWIFI_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/wifipmod_PmodWIFI_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_PmodWIFI_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_PmodWIFI_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/wifipmod_PmodWIFI_0_0.xci
# IP: The module: 'wifipmod_PmodWIFI_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}]

# IP: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/PmodWIFI_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_pmod_bridge_0_0 || ORIG_REF_NAME==PmodWIFI_pmod_bridge_0_0}] {/inst }]/inst ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/wifipmod_PmodWIFI_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_PmodWIFI_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_PmodWIFI_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_quad_spi_0_0/PmodWIFI_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_quad_spi_0_0 || ORIG_REF_NAME==PmodWIFI_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_0_0/PmodWIFI_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_0_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0_ooc.xdc

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_gpio_1_0/PmodWIFI_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_gpio_1_0 || ORIG_REF_NAME==PmodWIFI_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodWIFI_axi_timer_0_0 || ORIG_REF_NAME==PmodWIFI_axi_timer_0_0}] {/U0 }]/U0 ]]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/src/PmodWIFI_axi_timer_0_0/PmodWIFI_axi_timer_0_0_ooc.xdc
