# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0.xci
# IP: The module: 'wifipmod_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0.xci
# IP: The module: 'wifipmod_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/dev/workspace/zybo-wifi/zybo-wifi.srcs/sources_1/bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'wifipmod_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
