# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/wifipmod/wifipmod.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod || ORIG_REF_NAME==wifipmod}]

# IP: bd/wifipmod/ip/wifipmod_processing_system7_0_1/wifipmod_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_processing_system7_0_1 || ORIG_REF_NAME==wifipmod_processing_system7_0_1}]

# IP: bd/wifipmod/ip/wifipmod_axi_gpio_0_0/wifipmod_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_axi_gpio_0_0 || ORIG_REF_NAME==wifipmod_axi_gpio_0_0}]

# IP: bd/wifipmod/ip/wifipmod_axi_gpio_1_0/wifipmod_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_axi_gpio_1_0 || ORIG_REF_NAME==wifipmod_axi_gpio_1_0}]

# IP: bd/wifipmod/ip/wifipmod_ps7_0_axi_periph_0/wifipmod_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_ps7_0_axi_periph_0 || ORIG_REF_NAME==wifipmod_ps7_0_axi_periph_0}]

# IP: bd/wifipmod/ip/wifipmod_rst_ps7_0_100M_0/wifipmod_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_rst_ps7_0_100M_0 || ORIG_REF_NAME==wifipmod_rst_ps7_0_100M_0}]

# IP: bd/wifipmod/ip/wifipmod_xbar_0/wifipmod_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_xbar_0 || ORIG_REF_NAME==wifipmod_xbar_0}]

# IP: bd/wifipmod/ip/wifipmod_PmodWIFI_0_0/wifipmod_PmodWIFI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_PmodWIFI_0_0 || ORIG_REF_NAME==wifipmod_PmodWIFI_0_0}]

# IP: bd/wifipmod/ip/wifipmod_auto_pc_0/wifipmod_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wifipmod_auto_pc_0 || ORIG_REF_NAME==wifipmod_auto_pc_0}]

# XDC: bd/wifipmod/wifipmod_ooc.xdc
